# Generated by Django 4.1.4 on 2022-12-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='descripcion',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='contenido',
            field=models.TextField(null=True),
        ),
    ]
