# Generated by Django 4.1.4 on 2022-12-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posteo_descripcion_alter_posteo_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
