# Generated by Django 4.1.4 on 2022-12-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posteo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='posteo',
            name='copete',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
