# Generated by Django 4.1.4 on 2022-12-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_posteo_descripcion_posteo_copete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
