# Generated by Django 4.1.4 on 2022-12-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_posteo_slug_alter_posteo_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='imagen_encabezado',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
