# Generated by Django 4.1.4 on 2022-12-21 00:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_posteo_imagen_encabezado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='contenido',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
